### ISSUE TITLE
Implement matrix-matrix multiplication

### ISSUE THREAD

**Issue by dan-zheng** [feiwang3311/Lantern#12]
Matrix multiplication is an important primitive operation.
We can redefine convolution in terms of matmul when it's implemented.
matmul will become relevant when batches are supported.

---

Proactively assigning this to myself.
I'll submit a PR for a trivial (CPU) implementation within the next 3 days.
I'll then add GPU support as part of #8.

If someone needs matmul support before I get to it, please take over the issue 😄

**Comment by dan-zheng** [comment]
Design detail: I believe the existing `Tensor.dot` method should be extended to support matrix-matrix multiplication functionality (rather than implementing a new `Tensor.matmul` method).

This is consistent with popular machine learning libraries. `dot` will then support vec-vec, mat-vec, and mat-mat multiplication. In the future, the functionality of `dot` can be generalized to match [`tensordot`](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.tensordot.html).

**Comment by TiarkRompf** [comment]
Makes sense -- a generic `dot` method can delegate to AXPY, GEMM, ... based on tensor shape. A general question is if and how we want to deal with broadcasting semantics but I guess we can deal with that later.

**Comment by dan-zheng** [comment]
Whether to support broadcasting semantics is a good question. I'd like to support broadcasting because it improves usability and often leads to computation optimizations. (Broadcasting isn't relevant for matmul though, only elementwise binary ops.)

Some random resources, somewhat off-topic:
* ["Type-safe abstractions for Tensor Operations"](https://arxiv.org/pdf/1710.06892.pdf)
  * Shape-safe tensor operations, implemented using `HList` from [shapeless](https://github.com/milessabin/shapeless).
  * I would say this project makes immediate sense to Scala developers.
* ["dot broadcasting" in Julia](https://docs.julialang.org/en/v0.6.1/manual/functions/#man-vectorized-1)
* [The Julia language challenge](https://nextjournal.com/sdanisch/the-julia-language-challenge)

**Comment by TiarkRompf** [comment]
The broadcasting links are good reading. This probably warrants a separate discussion.
