### ISSUE TITLE
Investigate non-deterministic CI failures

### ISSUE THREAD

**Issue by dan-zheng** [feiwang3311/Lantern#19]
Travis CI is failing non-deterministically for some reason.
Usually it takes me 2-3 attempts of retriggering CI for tests to pass.

**Comment by dan-zheng** [comment]
From my observations, error messages differed from run to run. Here's one example:
```
[info] - add_broadcast4 *** FAILED ***
[info]   java.io.IOException: Cannot run program "/tmp/snippet": error=2, No such file or directory
[info]   at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[info]   at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:109)
[info]   at scala.sys.process.ProcessBuilder.lines(ProcessBuilder.scala:178)
[info]   at scala.sys.process.ProcessBuilder.lines$(ProcessBuilder.scala:178)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines(ProcessBuilderImpl.scala:87)
[info]   at lantern.DslDriverC.eval(dslapi.scala:501)
[info]   at lantern.BroadCastingTest.$anonfun$new$5(test_broadcast.scala:85)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
```

Perhaps [randomizing snippet filenames](https://github.com/feiwang3311/Lantern/commit/ab6b77605e41809f6d192dcc6abc8d495df6968e) fixes this issue. I'll observe and close this issue if that is the case.

**Comment by feiwang3311** [comment]
Yep. That was the same problem. My recent push should have used random name now.

**Comment by dan-zheng** [comment]
One downside to randomizing snippet filenames is that each test invocation generates a new file in `/tmp`. If tests are run many times, there'll be an explosion in the number of snippet files.

A better strategy may be to use the testcase name as the snippet filename, e.g. `test("vector-vector-dot") -> /tmp/vector-vector-dot.cpp`.

**Comment by TiarkRompf** [comment]
I think it's better to run tests sequentially anyways (for reproducibility) so let's just turn parallelism off (there's an sbt flag to do that, check LMS repo).

But let's also name files according to test names, as you suggest @dan-zheng.

**Comment by dan-zheng** [comment]
* [Parallel test execution disabled.](https://github.com/feiwang3311/Lantern/commit/5e2d6b9f1de91e2935a5923f96fb441f79a25641)
* [Reverted snippet filename randomization.](https://github.com/feiwang3311/Lantern/commit/d47f8afead2634604ff39242495837fb99a16e6a)
  * The root of the CI failures was parallel testing, not the shared snippet filename. Use a single deterministic filename is better for clarity.
