### ISSUE TITLE
Use JavaCPP Preset for ONNX and/or ONNX-Scala

### ISSUE THREAD

**Issue by EmergentOrder** [feiwang3311/Lantern#42]
The [JavaCPP Preset for ONNX](https://github.com/bytedeco/javacpp-presets/tree/master/onnx) contains everything that you get from the implementation generated from the protobuf that is currently used. You also get the ability to ["polish"](https://github.com/onnx/onnx/blob/v1.3.0/onnx/utils.py#L14) and convert the version of a model (in this [PR](https://github.com/bytedeco/javacpp-presets/pull/622) ) as well as access to the operator schemas, the ONNX IR, ONNX-ML (Classical Machine Learning extension), ONNXIFI and more.

The JavaCPP Preset offers an API that is as close as possible to the ONNX C++ API in Java.

In contrast, [ONNX-Scala](https://github.com/EmergentOrder/onnx-scala) aims to provide a typeful, idiomatic and purely functional Scala API to ONNX. ONNX-Scala makes full use of (sometimes bleeding-edge) language features where appropriate, while targeting 2 current and 2 in-development versions of Scala for the JVM, as well as Scala Native and Scala.js.

ONNX-Scala provides a clean separation between API, program definition, and backend implementation.

I intend to add a Lantern-based backend there soon, but you could implement the provided API here.

They will be published separately, so there would be no circular dependency. i.e. : ONNX-Scala API <- Lantern <- ONNX-Scala Lantern Backend

**Comment by EmergentOrder** [comment]
Thanks for the hard work on Lantern, by the way!

**Comment by feiwang3311** [comment]
Thanks for the constructive suggestions and encouragement. We will investigate this as soon as we sort out more urgent matters in our group. :)

**Comment by EmergentOrder** [comment]
@feiwang3311 @dan-zheng I've gone ahead and done the swap in favor of the JavaCPP Preset. The ONNX tests are passing. 
It generally boils down to a drop-in replacement, with some renaming and type changes required. There is one set of helper methods that I wrote that add a bunch of code, but I will aim to refactor into a single, small method, and some other minor cleanup to do. I should have a PR for you in a few days.

**Comment by feiwang3311** [comment]
Thanks! I merged your PR. :)
