### ISSUE TITLE
ONNX Support

### ISSUE THREAD

**Issue by TiarkRompf** [feiwang3311/Lantern#7]
- [X] Basic ONNX format reading
- [X] Implement inference and training for SqueezeNet
- [x] Verify results with reference, add corresponding unit tests

**Comment by TiarkRompf** [comment]
All done? Cool! Do we have a commit that we can reference as completing the ticket? It also seems the onnx branch is still around. Can it be merged into master?

**Comment by feiwang3311** [comment]
This commit 7b16cab551e7683cb7a126ef961f2757acad154a can server as the reference. 
The onnx branch may keep around for a while. I want to develop other models (such as resnet).
Be noted that I haven't done training experiment with Squeezenet. My correctness guarantee is based on simple unit test and correct inference result.

**Comment by TiarkRompf** [comment]
But the functionality for training (SqueezeNet or others) is implemented? We still need to verify that training actually works, but perhaps it's more meaningful with the GPU backend anyways.

In any case we should delete this branch (it's merged into master I assume?). New models will be part of #9 and we should branch off of master again for those.
